"""add_surat_jalan_and_material_datang_paths_to_stock_ins

Revision ID: 2bcb46d867a0
Revises: (base)
Create Date: 2025-10-31 22:37:33.876207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2bcb46d867a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_ins', sa.Column('surat_jalan_paths', sa.Text(), nullable=True))
    op.add_column('stock_ins', sa.Column('material_datang_paths', sa.Text(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('ADMIN', 'GUDANG', 'MANDOR', name='userrole'),
               existing_nullable=False,
               existing_server_default=sa.text("'gudang'"))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'GUDANG', 'MANDOR', name='userrole'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'gudang'"))
    op.drop_column('stock_ins', 'material_datang_paths')
    op.drop_column('stock_ins', 'surat_jalan_paths')
    # ### end Alembic commands ###
